### ISSUE TITLE
first load takes >1s 

### ISSUE THREAD

**Issue by mgenev** [ListnPlay/riot-isomorphic#10]
This is all really cool, but why is the initial load so slow?

<img width="707" alt="screen shot 2015-10-12 at 6 54 21 pm" src="https://cloud.githubusercontent.com/assets/3029803/10443693/906535ec-7112-11e5-8f81-7cc6beef9c2c.png">

my express + dust js project returns first load in 0.15s
<img width="705" alt="screen shot 2015-10-12 at 6 56 55 pm" src="https://cloud.githubusercontent.com/assets/3029803/10443715/d2f83670-7112-11e5-9e70-859614836ba7.png">

**Comment by Avnerus** [comment]
Hi and thanks for the feedback!
There is actually an intentional slowdown on the server side here:
https://github.com/ListnPlay/riot-isomorphic/blob/master/src/server/services/fruit.js#L4

I added this delay so I could test my `waitBeforeRendering` feature. That way you can see that the server side rendering is not returned to the client before the fruit service responded.

**Comment by mgenev** [comment]
ah you are correct, i disabled the time out and the speed is awesome, thanks! this is great learning for me and I'm hoping to use it for a big project

**Comment by Avnerus** [comment]
My pleasure :)
